name: Start detect-releases.yml
# Required because making a matrix element conditional is difficult
# https://stackoverflow.com/questions/65384420/how-do-i-make-a-github-action-matrix-element-conditional

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 0" # Runs every Sunday at 8AM UTC



jobs:
  stable:
    name: Check stable release
    uses: ./.github/workflows/detect-releases.yml
    with:
      channel: stable
